### ISSUE TITLE
Add WLED-Quinled-board-MQTT to WLED/usermods

### ISSUE THREAD

**Issue by huggy-d1** [400killer/WLED-Quinled-board-MQTT#2]
Aircookie created a new folder on the WLED github for usermods like yours.
It would be much appreciated if your usermod were added (when you have time).

**Comment by 400killer** [comment]
Thanks huggy-d1! I did not see that folder. I will keep a copy there, as most will more easily find it there. I hope the code is working for you, I am new to posting on GitHub, and programming.

**Comment by 400killer** [comment]
Also per a suggestion, I am modifying the code to due both F and C if that helps you too.
